# 为微服务分配端口
server:
  port: 11000

# 配置数据库连接信息
spring:
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://10.24.82.90/gulimall_pms?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: ***
      secret-key: ***
      oss:
        endpoint: oss-cn-shenzhen.aliyuncs.com

# 配置mybatis的xml文件的位置
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml  # classpath后面的*表示，不仅扫面自己的classpath，也扫描所有依赖的classapth
  # 选择使用主键自增，之后分库分表可能需要回来修改这里
  global-config:
    db-config:
      id-type: auto
      # logic-delete-field: show_status  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

# 调整日志级别，展示mybatis修操作数据库的SQL语句
logging:
  level:
    com.ljl.gulimall: debug
